import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";
import Vector from "../app/assets/image/vector-1.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased  text-white  mx-auto `}>
        <div className="w-full max-w-[1440px] m-auto px-5 md:px-8 lg:px-[120px] pb-8 md:pb-12 xl:pb-[109px]">
          {children}
          <Toaster richColors />
        </div>
        <Image src={Vector} alt="vector " className="w-full" />
      </body>
    </html>
  );
}
